### PR TITLE
Bye ruby hello fantasticon

### PR DESCRIPTION
**Pull request by gijs**
Hello,

I could no longer get the original setup to work using Ruby etc.

This PR introduces [Fantasticon](https://github.com/tancredi/fantasticon), a JS tool to do the same thing, generate an iconfont from a bunch of SVG's.  Also adds a Github action to auto-build and publish.

Looks like this:

Screenshot 2021-12-06 at 13 28 18

One thing that doesnt seem right is the pipe icon:
Screenshot 2021-12-06 at 13 22 12

Other than that I think this is a good upgrade and makes adding new icons as simple as commiting it to the `originals/` directory. It also generates Typescript, a preview page etc.

Please run locally, steps are in README.md. 

Let me know if it doesnt work.

Thx

### CODE REVIEW

**Comment by reinout** [comment]
I see you're committing the *generated* `dist/` files to the repo. I'd initially expect that to be git-ignored?

**Comment by gijs** [comment]
That's a logical assumption @reinout
The current setup also commits the `dist/` directory, I guess this was done so that the generated iconfont becomes part of the zipfile under Releases.
I think Lizard also expects it to be there.

A better way would be to use the Github assets API for the generated files.

**Review by byrman — COMMENTED** [review]
Die .sass-cache ziet eruit als iets dat niet onder versiebeheer had moeten staan? Fijn dat dat nu wordt opgeruimd.

Mijn vragen gaan over de integratie met Lizard. Er zijn 2 plaatsen waar naar lizard-iconfont wordt verwezen:
```
./package.json:        "lizard-iconfont": "git+https://github.com/nens/lizard-iconfont.git#1.3.7",
./lizard_nxt/management/commands/convert_carto_mss.py:                node_modules + "/lizard-iconfont/fonts",
```
Moeten er dingen in lizard-nxt worden aangepast als deze pull request wordt gemerged?

**Comment by Derryrover** [comment]
Looks good!
We might need to create tickets for tests with dependent repo's (lizard-client and others?)

I created a pull request in klimaat-monitor to add this icon-font and it works:
https://github.com/nens/klimaat-monitor/pull/48/files
But not sure if how I did it for klimaat-monitor is the preferred way.
I included the css and font files in the repo of klimaat-monitor,
but maybe we like to instead retrieve them from an online source?

At the moment I do not really have a preference.
In future I would prefer a business user (concultant, 1st line support, etcetera) to be able to fix small problems with icons or images without developer interference. But maybe this is too far fetched for now.

Ps:
If adding css and font-files to the client-repo is the preferred way then we must maybe mention in the readme that the user should also copy the font-files to the client-repo (.woff files etcetera).

**Comment by gijs** [comment]
thx for your reviews!

@byrman I think it's easier / safer to adapt the output of this project to what Lizard expects... I see Lizard expects an the iconfont in a `fonts/` directory.. I will look into this to make sure it adheres to Lizards expectation.

@Derryrover I don't think what you're saying is far fetched.. it is essential imho. The github action included should be able to generate a new iconfont when a new svg icon gets added via a Pull Request (or even directly). 
A next step should be to copy that output into an S3 (or S3 compat object store) bucket, and serve it via a CDN. 
I think that will really pay off in terms of perf.

Tom, perhaps you can create the tickets for this? If you don't have time I can do it too, but this was supposed to be a lunch-break thing for me :)

**Review by byrman — APPROVED** [review]

**Pull request merged**
